update to nightly-2017-01-25
This was pretty smooth and painless, mostly fixing up global variable
names to be all caps b/c that's caught now and a few structures got
smaller (whoo!)

One gotcha, the `#[lang=panic_fmt]` now requires you to also add a
`#[no_mangle]` directive, otherwise the symbol will be dropped and
you'll get an undefined reference to `rust_begin_unwind` (which is
what our `panic_fmt` function gets silently renamed to courtesy of
the magic of `#[lang=panic_fmt]`).
More info at https://github.com/rust-lang/rust/issues/38281

An unresolved mystery, imix currently gives this warning:

    warning: function panic_fmt is marked #[no_mangle], but not exported,
    #[warn(private_no_mangle_fns)] on by default
      --> src/io.rs:40:1
       |
    40 | pub unsafe extern "C" fn panic_fmt(args: Arguments, file: &'static str, line: u32) -> ! {
       | ^

Now, of course, removing no_mangle will result in the undefined
reference as described above, with it this at least compiles, unclear
what's different about imix than the other platforms that don't throw
this warning.

Run-tested on hail. Compile-tested on every other platform.